### ISSUE TITLE
git operation not respecting gitignore

### ISSUE THREAD

**Issue by tonglil** [joelanford/go-apidiff#20]
Trying to run this locally, it gets stuck because the local repository is considered dirty as it's not parsing the gitignore.

```
go-apidiff origin/main --repo-path=./ --print-compatible
current git tree is dirty
?? doc/.DS_Store
?? schema/.DS_Store
?? .DS_Store
```

It should also only consider diffing `*.go` files, even if other files are dirty.

Another use case is in our CI, we vendor dependencies, so it detects `vendor/` as dirty.

https://github.com/go-git/go-git/issues/500
https://github.com/go-git/go-git/issues/387

**Comment by joelanford** [comment]
> as it's not parsing the gitignore.

That's unfortunate! Let's leave this open so we can bump our go-git version when that issue is resolved.

> It should also only consider diffing *.go files, even if other files are dirty.

The primary reason it bails out on a dirty tree is that it actually has to checkout the old commit, read its packages, and then re-checkout the original commit, thus leaving no trace. Perhaps there's a safe/clean way to stash the dirty tree, and then unstash it, but I was intentionally trying to be conservative to avoid messing up folks' repos.

> Another use case is in our CI, we vendor dependencies, so it detects vendor/ as dirty.

The workarounds there, I think, are:
1. Run `go-apidiff` prior to vendoring (or in a separate CI job).
2. Commit the vendor directory.

**Comment by tonglil** [comment]
Thanks for acknowledging Joe.

> I was intentionally trying to be conservative to avoid messing up folks' repos.

I see, that makes sense! I'll have to think about how to clean the tree beforehand, perhaps `git clean -fdx`.

Yeah we are running it before vendoring :)

**Comment by tonglil** [comment]
Running into an issue where I'm not sure how I can get the program to run locally.

The problem is that I'm not going to commit `.DS_Store` files, yet I can't get this tool to ignore them. When I try to delete `.DS_Store` files, the computer regenerates them..

**Comment by npepinpe** [comment]
You could try using [work trees](https://git-scm.com/docs/git-worktree), that would allow you to check out locally a specific commit to a temporary directory without having to clean anything.
