### ISSUE TITLE
go-apidiff is not recognizing major update in the package.

### ISSUE THREAD

**Issue by wtrocki** [joelanford/go-apidiff#37]
## Problem

In situations when go-apidiff is run on branch that has new major release compared to base branch goapidiff will report breaking changes containing entire API.

## Steps to reproduce

Bump the version in the go.mod file and update imports. 
Create PR that runs Go-APIdiff

**Comment by joelanford** [comment]
Can you point me to a public repo with two branches that exhibit this problem? I'm not sure I'm following.

**Comment by wtrocki** [comment]
PR: https://github.com/mongodb/atlas-sdk-go/pull/188  
Job: https://github.com/mongodb/atlas-sdk-go/actions/runs/6161067457/job/16719438764

I debugged issue and it feels like problem with the underlying diff library design. 
When a new major version is introduced it will still produce diff. 
I think fix is to document case of major release is to susped running action or ignore results.

**Comment by joelanford** [comment]
Ah, it seems like the it is failing because the module path changed (to account for the new major version?). So from go-apidiff's perspective, an entire tree of APIs (`v20230201006`) was dropped.

I'm a little fuzzy on this. Can your users continue importing `go.mongodb.org/atlas-sdk/v20230201006` after this PR merged?

**Comment by joelanford** [comment]
> Go recomends separate branches for each version to live their own life.

Right, but this looks to me like a PR where one directory is removed and another directory is added in the context of a single base branch that the PR is targeting (`main`). In that context, go-apidiff output is correct and expected.

> I'm a little fuzzy on this. Can your users continue importing go.mongodb.org/atlas-sdk/v20230201006 after this PR merged?

It seems like this is no longer importable on the `main` branch though, so for anyone/anything consuming the main branch (e.g. non-gomodule-aware tooling), this is a breaking change. FWIW, the go maintainers suggest using subdirectories instead of branches for multiple major versions (https://go.dev/blog/v2-go-modules), but I acknowledge that has it's own oddities and complexity.

> I think we can close this issue as there is not much we can do about this in goapidiff (unless we want to document it)

Sounds good. Not sure how you feel, but this feels to me like an edge case of your particular repository's versioning strategy that would be hard to document without being confusing for the general case.
