### ISSUE TITLE
Distribute go-apidiff as CLI

### ISSUE THREAD

**Issue by wtrocki** [joelanford/go-apidiff#38]
go-apidiff acts as github actions but it also provides very nice CLI.
Github action is very specific and doesn't enable much customization in place. 

See: #32 

## Proposal

Add CLI binaries as part of the releases would enable others to use CLI along with the github actions.

# Alternatives

building CLI using go get/go install.

**Comment by joelanford** [comment]
See https://github.com/joelanford/go-apidiff#local-installation for instructions on installing locally to use as a CLI.

Lots of go-apidiff users are already going this route, e.g. if they use a CI tool other than GitHub actions.

I'd rather not maintain build/release tooling to support pre-built binaries since the "go install" method is so robust.
